In [2]:
import numpy as np
import pandas as pd

In [40]:
#loading the dataset in noteook
df = pd.read_excel(r"C:\Users\anshu\OneDrive\Pictures\Documents\Combined_dataset1.csv.xlsx")

In [41]:
#exploring the dataset 
#1 
print(df.head())


#2 shape of dataset
print(f"Dataset Shape (Rows, Columns): {df.shape}")

#3 tail of the dataset(last 5 rows)
print("--- LAST 5 ROWS ---")
display(df.tail())

#4 summary of the dataset
print(" DATASET  SUMMARY")
print(df.info())

   product_id           title                         product_description  \
0     8376765     Lino Perros              Women Navy Blue Solid Backpack
1     9136281  Tommy Hilfiger           Unisex Navy Blue Striped Backpack
2    17633752           Lavie              Aries Women Pink Mini Backpack
3     1376949          F Gear  Unisex Navy & Grey Printed Burner Backpack
4    13939916       MYTRIDENT                    Men Blue Solid Bath Robe

   rating  ratings_count  initial_price  discount    final_price currency  \
0     3.8             15           3995      58.0  "â‚¹3,995.00"      INR
1     4.5             67           2899      35.0  "â‚¹2,899.00"      INR
2     4.4            226           2999      65.0  "â‚¹2,999.00"      INR
3     4.4           1052           1675      52.0  "â‚¹1,675.00"      INR
4     4.7             12           2899      17.0  "â‚¹2,899.00"      INR

                                              images  ...  \
0  http://assets.myntassets.com/assets/images/837...  ...
1  http://assets.myntassets.com/assets/images/913...  ...
2  http://assets.myntassets.com/assets/images/176...  ...
3  http://assets.myntassets.com/assets/images/137...  ...
4  http://assets.myntassets.com/assets/images/pro...  ...

                                     amount_of_stars what_customers_said  \
0  {"1_star":2,"2_stars":0,"3_stars":3,"4_stars":...                 NaN
1  {"1_star":3,"2_stars":4,"3_stars":2,"4_stars":...                 NaN
2  {"1_star":9,"2_stars":5,"3_stars":10,"4_stars"...                 NaN
3  {"1_star":33,"2_stars":21,"3_stars":69,"4_star...                 NaN
4  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN

  seller_name                                              sizes  \
0         NaN                               [{"size":"Onesize"}]
1         NaN                               [{"size":"Onesize"}]
2         NaN                                     [{"size":"S"}]
3         NaN                               [{"size":"Onesize"}]
4         NaN  [{"size":"M","value":"45.0in","value_name":"Fr...

                                              videos seller_information  \
0                              ["rw-8376765_cae700"]                NaN
1                              ["rw-9136281_cae700"]                NaN
2  ["https://videos.myntassets.com/assets/videos/...                NaN
3  ["https://videos.myntassets.com/assets/videos/...                NaN
4                                                NaN                NaN

                                    variations best_offer  \
0                                         [{}]         {}
1                                      [{},{}]         {}
2                          [{},{},{},{},{},{}]         {}
3                                          NaN         {}
4  [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]         {}

                                         more_offers   category
0  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
1  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
2  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
3  [{"offer_name":"10% Instant Discount on Citi C...  backpacks
4  [{"offer_name":"10% Instant Discount on IndusI...  bath-robe

[5 rows x 24 columns]
Dataset Shape (Rows, Columns): (1000, 24)
--- LAST 5 ROWS ---

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""â‚¹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""â‚¹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""â‚¹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""â‚¹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Truâ–ˆâ–ˆâ–ˆm Râ–ˆâ–ˆâ–ˆil,"[{""size"":""Onesize""}]",NaN,Shoâ–ˆâ–ˆâ–ˆo. â–ˆâ–ˆâ–ˆ-10â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""â‚¹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

 DATASET  SUMMARY
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB
None

In [42]:
# handling the the dataset
print("Blanks per column before handling:")
print(df.isnull().sum())
print("-" * 50)

# Create a copy
df_cleaned = df.copy()

#handing the missing values
df_cleaned['discount'] = df_cleaned['discount'].fillna(0)
df_cleaned['seller_name'] = df_cleaned['seller_name'].fillna('Unknown Seller')
df_cleaned['what_customers_said'] = df_cleaned['what_customers_said'].fillna('No Review Summary')
df_cleaned['videos'] = df_cleaned['videos'].fillna('No Video Available')
df_cleaned['seller_information'] = df_cleaned['seller_information'].fillna('No Seller Info')
df_cleaned['variations'] = df_cleaned['variations'].fillna('Standard Variant')

print("Missing values handled -Remaining null data", df_cleaned.isnull().sum().sum())

Blanks per column before handling:
product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64
--------------------------------------------------
Missing values handled -Remaining null data 0

In [43]:
# -> step 4 performing operations

#1
print("SELECTING COLUMNS")
display(df_cleaned[['title', 'initial_price', 'rating', 'category']].head())


#2
print("RATING GREATER THAN 3.0")
filtered_rating_df = df_cleaned[df_cleaned['rating'] > 3.0]
display(filtered_rating_df[['title', 'rating', 'final_price']].head())

print(filtered_rating_df.info())




#3 unique catagorie
print("ALL UNIQUE CATEGORIES IN THE DATASET:")
print(filtered_rating_df['category'].unique())


#4 highest prices
print("TOP 5 MOST EXPENSIVE PRODUCTS (SORTED BY PRICE)")
sorted_price_df = filtered_rating_df.sort_values(by='initial_price', ascending=False)
display(sorted_price_df[['title', 'initial_price', 'rating', 'category']].head())



#5 SAMPLES FROM THE MIDDLE OF THE DATASET
print("RANDOM SAMPLE OF 5 ROWS")
display(filtered_rating_df[['title', 'initial_price', 'rating']].sample(5))

SELECTING COLUMNS

            title  initial_price  rating   category
0     Lino Perros           3995     3.8  backpacks
1  Tommy Hilfiger           2899     4.5  backpacks
2           Lavie           2999     4.4  backpacks
3          F Gear           1675     4.4  backpacks
4       MYTRIDENT           2899     4.7  bath-robe

RATING GREATER THAN 3.0

            title  rating    final_price
0     Lino Perros     3.8  "â‚¹3,995.00"
1  Tommy Hilfiger     4.5  "â‚¹2,899.00"
2           Lavie     4.4  "â‚¹2,999.00"
3          F Gear     4.4  "â‚¹1,675.00"
4       MYTRIDENT     4.7  "â‚¹2,899.00"

<class 'pandas.DataFrame'>
Index: 852 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              852 non-null    int64
 1   title                   852 non-null    str
 2   product_description     852 non-null    str
 3   rating                  852 non-null    float64
 4   ratings_count           852 non-null    int64
 5   initial_price           852 non-null    int64
 6   discount                852 non-null    float64
 7   final_price             852 non-null    str
 8   currency                852 non-null    str
 9   images                  852 non-null    str
 10  delivery_options        852 non-null    str
 11  product_details         852 non-null    str
 12  breadcrumbs             852 non-null    str
 13  product_specifications  852 non-null    str
 14  amount_of_stars         852 non-null    str
 15  what_customers_said     852 non-null    str
 16  seller_name             852 non-null    str
 17  sizes                   852 non-null    str
 18  videos                  852 non-null    str
 19  seller_information      852 non-null    str
 20  variations              852 non-null    str
 21  best_offer              852 non-null    str
 22  more_offers             852 non-null    str
 23  category                852 non-null    str
dtypes: float64(2), int64(3), str(19)
memory usage: 166.4 KB
None
ALL UNIQUE CATEGORIES IN THE DATASET:
<StringArray>
[              'backpacks',               'bath-robe',
    'bathroom-accessories',             'bath-towels',
               'bedsheets',                   'belts',
                'bodysuit',                   'boots',
                  'boxers',                     'bra',
                'bracelet',                  'briefs',
               'camisoles',                    'caps',
            'casual-shoes',             'chair-cover',
            'clothing-set',                'clutches',
                 'co-ords',     'curtains-and-sheers',
                 'cutlery',              'dinnerware',
                 'dresses',              'duffel-bag',
               'dungarees',                 'dupatta',
                'earrings',          'ethnic-dresses',
       'face-moisturisers',  'face-wash-and-cleanser',
                   'flats',              'flip-flops',
    'floor-mats--dhurries',            'formal-shoes',
              'foundation',                  'gloves',
     'hair-brush-and-comb',     'hair-cream-and-mask',
              'hair-masks',                'handbags',
              'headphones',                   'heels',
      'home-fragrance-set',         'innerwear-vests',
                 'jackets',                   'jeans',
                'jumpsuit',                  'kurtas',
              'kurta-sets',                  'kurtis',
                'lipstick',            'lounge-pants',
           'lounge-shorts',          'lounge-tshirts',
             'mangalsutra',              'nightdress',
             'night-suits',           'outdoor-masks',
                'palazzos',   'perfume-and-body-mist',
           'pillow-covers',                    'ring',
                 'runners',                 'sandals',
            'saree-blouse',                  'sarees',
                 'scarves', 'shampoo-and-conditioner',
      'shaving-essentials',                'sherwani',
                  'shirts',                  'shorts',
                  'skirts',            'sports-shoes',
                'sweaters',             'sweatshirts',
               'swim-tops',            'table-covers',
         'thermal-bottoms',                  'tights',
                    'tops',               'towel-set',
             'track-pants',             'trolley-bag',
                'trousers',                   'trunk',
                 'tshirts',                  'tunics',
                'wall-art',                 'wallets',
                 'watches',               'yoga-mats']
Length: 92, dtype: str
TOP 5 MOST EXPENSIVE PRODUCTS (SORTED BY PRICE)

            title  initial_price  rating      category
985          MVMT          20832     4.5       watches
724        ADIDAS          18999     4.3  sports-shoes
920  Nasher Miles          17995     3.3   trolley-bag
716        ADIDAS          16999     3.9  sports-shoes
550         KISAH          16199     3.8      sherwani

RANDOM SAMPLE OF 5 ROWS

               title  initial_price  rating
931             XYXX            339     4.2
571            WROGN           2599     4.1
355  U.S. Polo Assn.           5999     4.0
1     Tommy Hilfiger           2899     4.5
160    all about you           1999     4.3

In [44]:
# -> STEP  5 REMOVE DUPLICATES

# 1. Count the duplicate rows 
duplicate_count = filtered_rating_df.duplicated().sum()

# 2.
if duplicate_count == 0:
    print("No duplicate data found.")
else:
    print(f"removing the duplicate rows : duplicate found ->{duplicate_count}")
    filtered_rating_df = filtered_rating_df.drop_duplicates()
    print(f"Deduplication complete. Current shape: {filtered_rating_df.shape}")

No duplicate data found.

In [45]:
# --- STEP 6: CREATE THE DERIVED COLUMN ---

# Calculate the total_amount directly onto your filtered data rows
filtered_rating_df['total_amount'] = filtered_rating_df['initial_price'] * (filtered_rating_df['discount'] / 100)

# Verify that the calculation column has been added perfectly
display(filtered_rating_df[['title', 'initial_price', 'discount', 'total_amount']].head())
print(filtered_rating_df.info())

            title  initial_price  discount  total_amount
0     Lino Perros           3995      58.0       2317.10
1  Tommy Hilfiger           2899      35.0       1014.65
2           Lavie           2999      65.0       1949.35
3          F Gear           1675      52.0        871.00
4       MYTRIDENT           2899      17.0        492.83

<class 'pandas.DataFrame'>
Index: 852 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              852 non-null    int64
 1   title                   852 non-null    str
 2   product_description     852 non-null    str
 3   rating                  852 non-null    float64
 4   ratings_count           852 non-null    int64
 5   initial_price           852 non-null    int64
 6   discount                852 non-null    float64
 7   final_price             852 non-null    str
 8   currency                852 non-null    str
 9   images                  852 non-null    str
 10  delivery_options        852 non-null    str
 11  product_details         852 non-null    str
 12  breadcrumbs             852 non-null    str
 13  product_specifications  852 non-null    str
 14  amount_of_stars         852 non-null    str
 15  what_customers_said     852 non-null    str
 16  seller_name             852 non-null    str
 17  sizes                   852 non-null    str
 18  videos                  852 non-null    str
 19  seller_information      852 non-null    str
 20  variations              852 non-null    str
 21  best_offer              852 non-null    str
 22  more_offers             852 non-null    str
 23  category                852 non-null    str
 24  total_amount            852 non-null    float64
dtypes: float64(3), int64(3), str(19)
memory usage: 173.1 KB
None

In [46]:
# Save the clean file 
df_cleaned.to_csv(r"C:\Users\anshu\OneDrive\Desktop\Cleaned_Combined_dataset1.csv", index=False)

print("project complete")

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\anshu\\OneDrive\\Desktop\\Cleaned_Combined_dataset1.csv'